apiVersion: v1
kind: Secret
metadata:
  name: mariadb-credentials
  namespace: mariadb
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: mariadb
type: Opaque
stringData:
  MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
  MARIADB_USER: homelab
  MARIADB_PASSWORD: ""
  MARIADB_DATABASE: homelab
