apiVersion: v1
kind: Secret
metadata:
  name: mariadb-credentials
  namespace: mariadb
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: mariadb
type: Opaque
stringData:
  # Change these before applying!
  MARIADB_ROOT_PASSWORD: changeme
  MARIADB_USER: homelab
  MARIADB_PASSWORD: changeme
  MARIADB_DATABASE: homelab
