apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: mongodb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: mongo
